include:
  - project: parob/gitlab-ci-templates
    file: "python.yml"
    
variables:
  AUTO_TAG_DEFAULT_BRANCH_ON_COMMIT: "true"
  PUBLISH_PYPI_USERNAME: ${PYPI_USERNAME}
  PUBLISH_PYPI_PASSWORD: ${PYPI_PASSWORD}
  PUBLISH_PYPI_REPOSITORY: ${PYPI_REPOSITORY}
