variables:
  AUTO_TAG_AND_PUBLISH_DEFAULT_BRANCH: "true"
  PUBLISH_PYPI_REPOSITORY: "PYPI"
  PUBLISH_PYPI_USERNAME: $PYPI_USERNAME
  PUBLISH_PYPI_PASSWORD: $PYPI_PASSWORD

include:
  - project: parob/gitlab-ci-templates
    file: "python.yml"
