image: "python:3.9"

stages:
  - test
  - deploy

lint:
  stage: test
  before_script:
    - pip install pipenv
    - pipenv install --dev
  script:
    - pipenv run python -m flake8 graphql_api

unit test:
  stage: test
  before_script:
    - pip install pipenv
    - pipenv install --dev
  script:
    - pipenv run python -m pytest tests --cov=graphql_api --cov-report=xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml


pages:
  stage: deploy
  before_script:
    - pip install pipenv
    - pipenv install --dev
  script:
    - pipenv run sphinx-build docs ./public -b html
  artifacts:
    paths:
    - public
  only:
    - /^v.*$/

deploy-pypi:
  stage: deploy
  before_script:
    - pip install twine
  script:
    - echo $CI_COMMIT_REF_NAME > VERSION
    - python setup.py sdist
    - twine upload dist/* -u $PYPI_USERNAME -p $PYPI_PASSWORD
  only:
    - /^v.*$/
